### ISSUE TITLE
I have no clue what im doing hhahahaha

### ISSUE THREAD

**Issue by kyleellis14** [kyleellis14/ecommerce-pattern-library#3]
@mackenzierose

I don't know what I'm doing.

**Comment by MacKenzieRose** [comment]
Hey Kyle!

So I reread the messages you sent me, and I'm not sure where you've tried to make banner content, but let me tell you what I **can** see.

First of all, your pages are working! Here's a screenshot of index.html. which you can view yourself if you run "http://localhost:4000/" in your browser:
<img width="926" alt="Screen Shot 2020-03-18 at 3 21 29 AM" src="https://user-images.githubusercontent.com/19557909/76967551-ff739180-68fd-11ea-933f-6d2d8c19665f.png">


So that's awesome. :)

If you look at the code you have in your index.html file, this is where I **think** the problems start. Because you've followed the lesson, you've got "{% pattern cards/banner %}" written. This tells your site to go into your patterns folder, into your cards folder, and to find a file called banner.html. But alas! No file by that name there. If you changed it to {% pattern banner/banner %}, it would find a banner.html, but there's no content in that file for it to render.


Let me know if that answered your question or not :)

Cheers!

MacKenzie

**Comment by kyleellis14** [comment]
<img width="1250" alt="Screen Shot 2020-03-18 at 11 38 27 AM" src="https://user-images.githubusercontent.com/43240374/76978414-06ee6700-690d-11ea-8a34-51404d6754ef.png">

this is what I can see

**Comment by kyleellis14** [comment]
ill commit everything im sorry!

**Comment by MacKenzieRose** [comment]
Okay so real quick in your banner config file, we need to change the dashes to be hyphens, not n dashes! With that small change, your banner.html in your pattern library should look like this:  

<img width="1260" alt="Screen Shot 2020-03-18 at 3 28 37 PM" src="https://user-images.githubusercontent.com/19557909/76999895-d1a64100-692d-11ea-8ab4-575ea0be1b27.png">

Then, when you embed this pattern into your index.html file, you'll need to define the heading and text elements that you're including. Here's an example and how it looks in the browser:

{% pattern banner/banner heading="This is a heading" text="This is text" %}

<img width="1273" alt="Screen Shot 2020-03-18 at 3 32 13 PM" src="https://user-images.githubusercontent.com/19557909/77000031-09ad8400-692e-11ea-93bb-8ecd72f7350b.png">
